In [1]:
import pandas as pd

In [2]:
from sqlite3 import connect

In [3]:
conn = connect(r"C:\Users\madas\Desktop\606\demo project\FPA_FOD_20170508.sqlite")

In [4]:
conn

In [5]:
data = pd.read_sql(sql = """SELECT name FROM sqlite_master  
  WHERE type='table';""",con = conn )

In [6]:

data

                                  name
0                      spatial_ref_sys
1                   spatialite_history
2                      sqlite_sequence
3                     geometry_columns
4                  spatial_ref_sys_aux
5               views_geometry_columns
6               virts_geometry_columns
7          geometry_columns_statistics
8    views_geometry_columns_statistics
9    virts_geometry_columns_statistics
10        geometry_columns_field_infos
11  views_geometry_columns_field_infos
12  virts_geometry_columns_field_infos
13               geometry_columns_time
14               geometry_columns_auth
15         views_geometry_columns_auth
16         virts_geometry_columns_auth
17                  sql_statements_log
18                        SpatialIndex
19                ElementaryGeometries
20                                 KNN
21                               Fires
22                     idx_Fires_Shape
23                idx_Fires_Shape_node
24               idx_Fires_Shape_rowid
25              idx_Fires_Shape_parent
26          NWCG_UnitIDActive_20170109

In [8]:
cursor = conn.cursor()

In [9]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

In [10]:
for table in tables:
    table_name = table[0]
    print(f"Columns for table: {table_name}")

Columns for table: spatial_ref_sys
Columns for table: spatialite_history
Columns for table: sqlite_sequence
Columns for table: geometry_columns
Columns for table: spatial_ref_sys_aux
Columns for table: views_geometry_columns
Columns for table: virts_geometry_columns
Columns for table: geometry_columns_statistics
Columns for table: views_geometry_columns_statistics
Columns for table: virts_geometry_columns_statistics
Columns for table: geometry_columns_field_infos
Columns for table: views_geometry_columns_field_infos
Columns for table: virts_geometry_columns_field_infos
Columns for table: geometry_columns_time
Columns for table: geometry_columns_auth
Columns for table: views_geometry_columns_auth
Columns for table: virts_geometry_columns_auth
Columns for table: sql_statements_log
Columns for table: SpatialIndex
Columns for table: ElementaryGeometries
Columns for table: KNN
Columns for table: Fires
Columns for table: idx_Fires_Shape
Columns for table: idx_Fires_Shape_node
Columns for table: idx_Fires_Shape_rowid
Columns for table: idx_Fires_Shape_parent
Columns for table: NWCG_UnitIDActive_20170109

In [13]:
# Correctly indented lines within a function
def my_function():
    cursor.execute("SELECT * FROM my_table")
    columns = cursor.fetchall()  # This line is at the correct indentation level within the function
    for column in columns:
        print(column)

In [15]:
# List of tables for which you want to read the data
# Replace this list with the names of your actual tables
tables = [
    'spatial_ref_sys',
    'spatialite_history',
    'sqlite_sequence',
    'geometry_columns',
    # Add the rest of your table names here...
]

# Iterate through each table and read its data
for table_name in tables:
    print(f"Data from table: {table_name}")
    
    try:
        cursor.execute(f"SELECT * FROM {table_name};")
        rows = cursor.fetchall()

        # Assuming you want to print the data, for example:
        for row in rows:
            print(row)
        
        print(f"Total rows in {table_name}: {len(rows)}")
        print("-" * 50)  # Just a separator for readability
        
    except sqlite3.Error as e:
        print(f"Error reading data from {table_name}: {e}")
        continue

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [7]:
for table in data['name']:
    try:
        in_data = pd.read_sql(sql = 'select * from '+table, con = conn)
        if table != 'SpatialIndex':
            print(table,in_data.shape)
    except:
        pass

spatial_ref_sys (4924, 6)
spatialite_history (16, 7)
sqlite_sequence (3, 2)
geometry_columns (1, 6)
spatial_ref_sys_aux (4873, 12)
views_geometry_columns (0, 6)
virts_geometry_columns (0, 5)
geometry_columns_statistics (1, 8)
views_geometry_columns_statistics (0, 8)
virts_geometry_columns_statistics (0, 8)
geometry_columns_field_infos (0, 14)
views_geometry_columns_field_infos (0, 14)
virts_geometry_columns_field_infos (0, 14)
geometry_columns_time (1, 5)
geometry_columns_auth (1, 4)
views_geometry_columns_auth (0, 3)
virts_geometry_columns_auth (0, 3)
sql_statements_log (0, 7)
Fires (1880465, 39)
idx_Fires_Shape (1880465, 5)
idx_Fires_Shape_node (72263, 2)
idx_Fires_Shape_rowid (1880465, 2)
idx_Fires_Shape_parent (72262, 2)
NWCG_UnitIDActive_20170109 (5867, 13)

In [10]:
fires_data = pd.read_sql(sql = 'select * from Fires', con = conn)

In [11]:
fires_data.head().T

,0,1,2,3,4
OBJECTID,1,2,3,4,5
FOD_ID,1,2,3,4,5
FPA_ID,FS-1418826,FS-1418827,FS-1418835,FS-1418845,FS-1418847
SOURCE_SYSTEM_TYPE,FED,FED,FED,FED,FED
SOURCE_SYSTEM,FS-FIRESTAT,FS-FIRESTAT,FS-FIRESTAT,FS-FIRESTAT,FS-FIRESTAT
NWCG_REPORTING_AGENCY,FS,FS,FS,FS,FS
NWCG_REPORTING_UNIT_ID,USCAPNF,USCAENF,USCAENF,USCAENF,USCAENF
NWCG_REPORTING_UNIT_NAME,Plumas National Forest,Eldorado National Forest,Eldorado National Forest,Eldorado National Forest,Eldorado National Forest
SOURCE_REPORTING_UNIT,0511,0503,0503,0503,0503
SOURCE_REPORTING_UNIT_NAME,Plumas National Forest,Eldorado National Forest,Eldorado National Forest,Eldorado National Forest,Eldorado National Forest
LOCAL_FIRE_REPORT_ID,1,13,27,43,44
LOCAL_INCIDENT_ID,PNF-47,13,021,6,7
FIRE_CODE,BJ8K,AAC0,A32W,None,None
FIRE_NAME,FOUNTAIN,PIGEON,SLACK,DEER,STEVENOT
ICS_209_INCIDENT_NUMBER,None,None,None,None,None
ICS_209_NAME,None,None,None,None,None
MTBS_ID,None,None,None,None,None
MTBS_FIRE_NAME,None,None,None,None,None
COMPLEX_NAME,None,None,None,None,None
FIRE_YEAR,2005,2004,2004,2004,2004
DISCOVERY_DATE,2453403.5,2453137.5,2453156.5,2453184.5,2453184.5
DISCOVERY_DOY,33,133,152,180,180
DISCOVERY_TIME,1300,0845,1921,1600,1600
STAT_CAUSE_CODE,9.0,1.0,5.0,1.0,1.0
STAT_CAUSE_DESCR,Miscellaneous,Lightning,Debris Burning,Lightning,Lightning
CONT_DATE,2453403.5,2453137.5,2453156.5,2453189.5,2453189.5
CONT_DOY,33.0,133.0,152.0,185.0,185.0
CONT_TIME,1730,1530,2024,1400,1200
FIRE_SIZE,0.1,0.25,0.1,0.1,0.1
FIRE_SIZE_CLASS,A,A,A,A,A
LATITUDE,40.036944,38.933056,38.984167,38.559167,38.559167
LONGITUDE,-121.005833,-120.404444,-120.735556,-119.913333,-119.933056
OWNER_CODE,5.0,5.0,13.0,5.0,5.0
OWNER_DESCR,USFS,USFS,STATE OR PRIVATE,USFS,USFS
STATE,CA,CA,CA,CA,CA
COUNTY,63,61,17,3,3
FIPS_CODE,063,061,017,003,003
FIPS_NAME,Plumas,Placer,El Dorado,Alpine,Alpine
Shape,b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0...,b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\...,b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\...,b'\x00\x01\xad\x10\x00\x00\x94\xac\xa3\rt\xfa]...,b'\x00\x01\xad\x10\x00\x00@\xe3\xaa.\xb7\xfb]\...

In [27]:
# Display basic information about the fires_data DataFrame
print("\nBasic information about Fires table:")
print(fires_data.info())

Basic information about Fires table:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1880465 entries, 0 to 1880464
Data columns (total 39 columns):
 #   Column                      Dtype
---  ------                      -----
 0   OBJECTID                    int64
 1   FOD_ID                      int64
 2   FPA_ID                      object
 3   SOURCE_SYSTEM_TYPE          object
 4   SOURCE_SYSTEM               object
 5   NWCG_REPORTING_AGENCY       object
 6   NWCG_REPORTING_UNIT_ID      object
 7   NWCG_REPORTING_UNIT_NAME    object
 8   SOURCE_REPORTING_UNIT       object
 9   SOURCE_REPORTING_UNIT_NAME  object
 10  LOCAL_FIRE_REPORT_ID        object
 11  LOCAL_INCIDENT_ID           object
 12  FIRE_CODE                   object
 13  FIRE_NAME                   object
 14  ICS_209_INCIDENT_NUMBER     object
 15  ICS_209_NAME                object
 16  MTBS_ID                     object
 17  MTBS_FIRE_NAME              object
 18  COMPLEX_NAME                object
 19  FIRE_YEAR                   int64
 20  DISCOVERY_DATE              float64
 21  DISCOVERY_DOY               int64
 22  DISCOVERY_TIME              object
 23  STAT_CAUSE_CODE             float64
 24  STAT_CAUSE_DESCR            object
 25  CONT_DATE                   float64
 26  CONT_DOY                    float64
 27  CONT_TIME                   object
 28  FIRE_SIZE                   float64
 29  FIRE_SIZE_CLASS             object
 30  LATITUDE                    float64
 31  LONGITUDE                   float64
 32  OWNER_CODE                  float64
 33  OWNER_DESCR                 object
 34  STATE                       object
 35  COUNTY                      object
 36  FIPS_CODE                   object
 37  FIPS_NAME                   object
 38  Shape                       object
dtypes: float64(8), int64(4), object(27)
memory usage: 559.5+ MB
None

In [28]:
# Display summary statistics
print("\nSummary statistics of numerical columns:")
print(fires_data.describe())

Summary statistics of numerical columns:
           OBJECTID        FOD_ID     FIRE_YEAR  DISCOVERY_DATE  \
count  1.880465e+06  1.880465e+06  1.880465e+06    1.880465e+06
mean   9.402330e+05  5.484020e+07  2.003710e+03    2.453064e+06
std    5.428436e+05  1.011963e+08  6.663099e+00    2.434573e+03
min    1.000000e+00  1.000000e+00  1.992000e+03    2.448622e+06
25%    4.701170e+05  5.055000e+05  1.998000e+03    2.451084e+06
50%    9.402330e+05  1.067761e+06  2.004000e+03    2.453178e+06
75%    1.410349e+06  1.910639e+07  2.009000e+03    2.455036e+06
max    1.880465e+06  3.003484e+08  2.015000e+03    2.457388e+06

       DISCOVERY_DOY  STAT_CAUSE_CODE     CONT_DATE       CONT_DOY  \
count   1.880465e+06     1.880465e+06  9.889340e+05  988934.000000
mean    1.647191e+02     5.979037e+00  2.453238e+06     172.656766
std     9.003891e+01     3.483860e+00  2.687548e+03      84.320348
min     1.000000e+00     1.000000e+00  2.448622e+06       1.000000
25%     8.900000e+01     3.000000e+00  2.450701e+06     102.000000
50%     1.640000e+02     5.000000e+00  2.453466e+06     181.000000
75%     2.300000e+02     9.000000e+00  2.455754e+06     232.000000
max     3.660000e+02     1.300000e+01  2.457392e+06     366.000000

          FIRE_SIZE      LATITUDE     LONGITUDE    OWNER_CODE
count  1.880465e+06  1.880465e+06  1.880465e+06  1.880465e+06
mean   7.452016e+01  3.678121e+01 -9.570494e+01  1.059658e+01
std    2.497598e+03  6.139031e+00  1.671694e+01  4.404662e+00
min    1.000000e-05  1.793972e+01 -1.788026e+02  0.000000e+00
25%    1.000000e-01  3.281860e+01 -1.103635e+02  8.000000e+00
50%    1.000000e+00  3.545250e+01 -9.204304e+01  1.400000e+01
75%    3.300000e+00  4.082720e+01 -8.229760e+01  1.400000e+01
max    6.069450e+05  7.033060e+01 -6.525694e+01  1.500000e+01

In [29]:
# Display first few rows of the Fires table
print("\nFirst few rows of the Fires table:")
print(fires_data.head())

First few rows of the Fires table:
   OBJECTID  FOD_ID      FPA_ID SOURCE_SYSTEM_TYPE SOURCE_SYSTEM  \
0         1       1  FS-1418826                FED   FS-FIRESTAT
1         2       2  FS-1418827                FED   FS-FIRESTAT
2         3       3  FS-1418835                FED   FS-FIRESTAT
3         4       4  FS-1418845                FED   FS-FIRESTAT
4         5       5  FS-1418847                FED   FS-FIRESTAT

  NWCG_REPORTING_AGENCY NWCG_REPORTING_UNIT_ID  NWCG_REPORTING_UNIT_NAME  \
0                    FS                USCAPNF    Plumas National Forest
1                    FS                USCAENF  Eldorado National Forest
2                    FS                USCAENF  Eldorado National Forest
3                    FS                USCAENF  Eldorado National Forest
4                    FS                USCAENF  Eldorado National Forest

  SOURCE_REPORTING_UNIT SOURCE_REPORTING_UNIT_NAME  ... FIRE_SIZE_CLASS  \
0                  0511     Plumas National Forest  ...               A
1                  0503   Eldorado National Forest  ...               A
2                  0503   Eldorado National Forest  ...               A
3                  0503   Eldorado National Forest  ...               A
4                  0503   Eldorado National Forest  ...               A

    LATITUDE   LONGITUDE OWNER_CODE       OWNER_DESCR STATE COUNTY FIPS_CODE  \
0  40.036944 -121.005833        5.0              USFS    CA     63       063
1  38.933056 -120.404444        5.0              USFS    CA     61       061
2  38.984167 -120.735556       13.0  STATE OR PRIVATE    CA     17       017
3  38.559167 -119.913333        5.0              USFS    CA      3       003
4  38.559167 -119.933056        5.0              USFS    CA      3       003

   FIPS_NAME                                              Shape
0     Plumas  b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0...
1     Placer  b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\...
2  El Dorado  b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\...
3     Alpine  b'\x00\x01\xad\x10\x00\x00\x94\xac\xa3\rt\xfa]...
4     Alpine  b'\x00\x01\xad\x10\x00\x00@\xe3\xaa.\xb7\xfb]\...

[5 rows x 39 columns]

In [30]:
# Print unique values in each column

print("\nUnique values in each column:")
for column in fires_data.columns:
    unique_values = fires_data[column].unique()
    print(f"{column}: {unique_values}")

Unique values in each column:
OBJECTID: [      1       2       3 ... 1880463 1880464 1880465]
FOD_ID: [        1         2         3 ... 300348375 300348377 300348399]
FPA_ID: ['FS-1418826' 'FS-1418827' 'FS-1418835' ... '2015CAIRS28364460'
 '2015CAIRS29218079' '2015CAIRS26733926']
SOURCE_SYSTEM_TYPE: ['FED' 'NONFED' 'INTERAGCY']
SOURCE_SYSTEM: ['FS-FIRESTAT' 'DOI-WFMI' 'FWS-FMIS' 'FA-NFIRS' 'ST-NASF' 'ST-AZAZS'
 'ST-MOMOS' 'IA-AKACC' 'ST-MTMTS' 'ST-SCSCS' 'ST-COCOS' 'ST-MEMES'
 'ST-ORORS' 'ST-MSMSS' 'ST-NMNMS' 'ST-SDSDS' 'ST-UTUTS' 'ST-WAWAS'
 'ST-WYWYS' 'ST-OKOKS' 'ST-WIWIS' 'ST-MIMIS' 'ST-KYKYS' 'ST-ALALS'
 'ST-ARARS' 'ST-GAGAS' 'ST-LALAS' 'ST-TNTNS' 'ST-VAVAS' 'ST-FLFLS'
 'ST-NCNCS' 'IA-ICS209' 'ST-CACDF' 'ST-CTCTS' 'ST-NENES' 'ST-TXTXS'
 'IA-PRIITF' 'IA-HIWMO']
NWCG_REPORTING_AGENCY: ['FS' 'BIA' 'TRIBE' 'BLM' 'NPS' 'BOR' 'FWS' 'ST/C&L' 'DOD' 'IA' 'DOE']
NWCG_REPORTING_UNIT_ID: ['USCAPNF' 'USCAENF' 'USCASHF' ... 'USPRPRS' 'USWYPLX' 'USHINPS']
NWCG_REPORTING_UNIT_NAME: ['Plumas National Forest' 'Eldorado National Forest'
 'Shasta-Trinity National Forest' ... 'Puerto Rico Fire Service'
 'Platte County' 'National Parks in Hawaii']
SOURCE_REPORTING_UNIT: ['0511' '0503' '0514' ... 'WYPLX' 'COH-HFD' 'HINPS']
SOURCE_REPORTING_UNIT_NAME: ['Plumas National Forest' 'Eldorado National Forest'
 'Shasta-Trinity National Forest' ...
 'County of Hawaii - Hawaii Fire Department' 'Honolulu Fire Dept'
 'National Parks in Hawaii']
LOCAL_FIRE_REPORT_ID: ['1' '13' '27' ... '574245' '570462' '535436']
LOCAL_INCIDENT_ID: ['PNF-47' '13' '021' ... '005748' '009371' '000366']
FIRE_CODE: ['BJ8K' 'AAC0' 'A32W' ... 'J5AS' 'J3NM' 'J48B']
FIRE_NAME: ['FOUNTAIN' 'PIGEON' 'SLACK' ... '1-64' 'ODESSA 2'
 'BARKER BL  BIG_BEAR_LAKE_']
ICS_209_INCIDENT_NUMBER: [None 'CA-ENF-017646' 'CA-ENF-18044' ... '010969' 'CA-LMU-2725' '474967']
ICS_209_NAME: [None 'POWER' 'FREDS' ... 'FORTY NINE' 'Swedes' 'Popcorn']
MTBS_ID: [None 'CA3850212028020041006' 'CA3878712031820041013' ...
 'CA3639412158320150919' 'CA3790512187420130908' 'CA3944512141720130816']
MTBS_FIRE_NAME: [None 'POWER' 'FREDS' ... 'CORRINE' 'TASSAJARA' 'SWEDES']
COMPLEX_NAME: [None 'THREE FIRE COMPLEX' 'GOLDILOCKS COMPLEX' ... 'HENDERSON COMPLEX'
 'LODGE COMPLEX' 'JAMUL COMPLEX']
FIRE_YEAR: [2005 2004 2006 2008 2002 2007 2009 2001 2003 1992 1993 1994 1995 1996
 1997 1998 1999 2000 2010 2011 2012 2013 2014 2015]
DISCOVERY_DATE: [2453403.5 2453137.5 2453156.5 ... 2457030.5 2457381.5 2457385.5]
DISCOVERY_DOY: [ 33 133 152 180 182 183  67  74 184 247 272 277 280 287 325 156 171 173
 177 202  78 218 132  36 243 285  64  70  27  37  43 106 129  95 157 165
  47  61 148 137 147  97 170 176  65 175 167 150 172 179 117 114 185 186
 122 149 136 178 104 169 191 190 138 188   2 195 126 189 162 115 199 196
 198 197 164  57 110 168 181 200 310 194 151 203  41  45 140 205 201 204
 207 174 192 208 209 143 100 111 123 153 193  87 210 154 163  93  96 103
 146 107  24  25  71 108 105 112 142 206 160 211 159 166 187 212  69  34
 214 155  40  42 158 124 127  76  94 161 217  68 215 219  75  98  99  23
 101  63 223 220 213  38  50 125 216 222 221 225  39 226 224 113  81  84
  92 145 228 229 128 134  22  30  32  12 231 139 118 233  48 135  58 232
 234 236  49 235  72  77  79  80  88 239 237  26  46 238 241  89  44 102
  60  15 242  66 240 227 244  55 119 252  51 248 246  90 250 251 109 130
 245 230  85 249 253 254 255 256 261 259 264 131 144 267 268 266 269 258
 262  91 257 260  73 275 271 265 263 120 273 270   3 141  62 281 276 282
 116 284 279 291 278 289 274 293 295 290  28  59 292 296 298 286  13 297
 283 300   5 304  86 121 306 294 309 288 305 308 303 312 313 299 315 307
 301 316 314 311 317 318  17  54  31  83   6 322 323 326 328 324 330 329
 331 332 320 321 319 327  10 336 333 335 338  21 339 340  11 341 346 302
 344 334  82  20 342 337 352 349 351 353 355 347  18 356 354 363   1 365
 361 362 348 350   4 357 364   7   9  16  14  19  52   8 343 345  35  29
 360  56  53 359 358 366]
DISCOVERY_TIME: ['1300' '0845' '1921' ... '0102' '0204' '0226']
STAT_CAUSE_CODE: [ 9.  1.  5.  4.  2.  7.  8.  6.  3. 11. 12. 10. 13.]
STAT_CAUSE_DESCR: ['Miscellaneous' 'Lightning' 'Debris Burning' 'Campfire' 'Equipment Use'
 'Arson' 'Children' 'Railroad' 'Smoking' 'Powerline' 'Structure'
 'Fireworks' 'Missing/Undefined']
CONT_DATE: [2453403.5 2453137.5 2453156.5 ... 2457386.5 2457391.5 2457388.5]
CONT_DOY: [ 33. 133. 152. 185. 183. 184.  67.  74. 247. 272. 277. 295. 291. 326.
 156. 171. 174. 178. 188. 202.  78. 218. 132.  37. 243. 285.  64.  70.
  28.  44. 106. 129.  95. 157. 165.  47.  61. 148. 137. 147.  97. 177.
 176.  65. 175. 168. 151. 172. 179. 117. 114. 186. 122. 149. 182. 136.
 104. 170. 191. 190. 138.  nan 189.   2. 195. 162. 173. 115. 196. 200.
 180. 199. 158. 198. 197. 164. 150. 167.  57. 110. 181. 310. 203.  41.
  45. 140. 204. 205. 194. 163. 207. 192. 208. 209. 145. 100. 111. 123.
 153. 201. 193.  87. 127. 210. 154.  93.  96. 169. 103. 146. 107.  24.
  25.  72.  98. 108. 211. 105. 112. 142. 206. 161. 212. 159. 166. 187.
 214.  69.  34. 143. 155.  40.  42. 124.  76. 217.  68. 216. 113.  94.
 220.  75.  99.  23.  88. 101.  66.  63. 222. 223. 213.  38.  50. 126.
  77. 144. 219. 221. 160. 225. 226.  89.  73. 224. 234. 227.  81.  84.
  92. 228. 109. 229. 215. 128. 134.  31.  32.  39.  13. 231. 139. 118.
 233.  48. 135.  59. 232. 236.  49. 235.  60.  71.  79.  80. 239.  22.
 237.  26.  46. 238. 241.  43. 102.  58.  62.  15. 242. 240. 244.  55.
 119. 120. 256.  53. 249. 246.  90. 248. 250. 252. 254. 251. 130. 245.
 116. 230.  85. 253. 255. 261. 259. 125. 264. 131. 267. 268. 262. 270.
 258. 269.  91. 257. 260. 275. 273. 266. 263. 276. 271.   5. 141.  51.
 265. 278. 282. 287. 279. 280. 292. 281. 284. 293. 274. 290. 299. 297.
 298. 283. 296. 304. 286. 300. 301.  86. 121. 306. 294. 309. 288. 305.
 289. 308. 303. 312. 313. 316. 315. 314. 311. 318. 307.  17.  54.   6.
 322. 320. 321. 332.  27. 323. 317. 324.  83. 328. 331. 329. 330. 333.
 334. 319. 335. 325. 327. 302.  10. 336. 347. 338.  21. 339. 340.  11.
 341. 346.  82.  20. 343. 337. 352. 350. 351. 355. 353. 344.  18. 356.
 354. 363. 349.   1. 365. 361. 362. 348.   4. 357. 364.   3.   7.   9.
  19. 358.  14.  29.  52.   8. 345.  35.  36. 360.  56.  12.  16.  30.
 342. 359. 366.]
CONT_TIME: ['1730' '1530' '2024' ... '0546' '0453' '']
FIRE_SIZE: [1.000e-01 2.500e-01 8.000e-01 ... 4.905e+02 8.220e+01 2.474e+01]
FIRE_SIZE_CLASS: ['A' 'B' 'G' 'C' 'D' 'F' 'E']
LATITUDE: [40.03694444 38.93305556 38.98416667 ... 40.481637   37.67223469
 34.263217  ]
LONGITUDE: [-121.00583333 -120.40444444 -120.73555556 ... -122.389375   -120.89835605
 -116.83095   ]
OWNER_CODE: [ 5. 13. 14.  6.  2.  4.  9.  8.  7.  1.  3. 10.  0. 12. 11. 15.]
OWNER_DESCR: ['USFS' 'STATE OR PRIVATE' 'MISSING/NOT SPECIFIED' 'OTHER FEDERAL' 'BIA'
 'FWS' 'TRIBAL' 'PRIVATE' 'STATE' 'BLM' 'NPS' 'BOR' 'FOREIGN'
 'MUNICIPAL/LOCAL' 'COUNTY' 'UNDEFINED FEDERAL']
STATE: ['CA' 'NM' 'OR' 'NC' 'WY' 'CO' 'WA' 'MT' 'UT' 'AZ' 'SD' 'AR' 'NV' 'ID'
 'MN' 'TX' 'FL' 'SC' 'LA' 'OK' 'KS' 'MO' 'NE' 'MI' 'KY' 'OH' 'IN' 'VA'
 'IL' 'TN' 'GA' 'AK' 'ND' 'WV' 'WI' 'AL' 'NH' 'PA' 'MS' 'ME' 'VT' 'NY'
 'IA' 'DC' 'MD' 'CT' 'MA' 'NJ' 'HI' 'DE' 'PR' 'RI']
COUNTY: ['63' '61' '17' ... 'Oahu' 'Molokaii' 'Lanai']
FIPS_CODE: ['063' '061' '017' '003' '005' None '027' '021' '113' '011' '009' '069'
 '037' '033' '053' '089' '049' '019' '023' '103' '043' '051' '039' '013'
 '025' '047' '031' '510' '007' '057' '001' '137' '091' '081' '071' '015'
 '035' '129' '006' '029' '075' '087' '065' '095' '105' '093' '055' '221'
 '059' '067' '165' '213' '153' '209' '123' '215' '077' '085' '169' '161'
 '045' '229' '041' '079' '028' '115' '107' '235' '109' '101' '147' '131'
 '099' '173' '181' '149' '203' '223' '125' '175' '179' '117' '097' '205'
 '163' '187' '195' '127' '151' '197' '083' '199' '122' '261' '291' '133'
 '237' '311' '241' '313' '121' '111' '073' '171' '257' '135' '119' '280'
 '110' '220' '130' '157' '201' '139' '281' '295' '189' '159' '141' '167'
 '145' '155' '339' '225' '471' '497' '407' '143' '020' '211' '403' '405'
 '419' '455' '347' '185' '193' '012' '177' '239' '243' '249' '259' '263'
 '269' '273' '307' '217' '219' '247' '297' '253' '275' '271' '279' '283'
 '309' '315' '207' '289' '303' '319' '231' '255' '285' '293' '227' '233'
 '030' '183' '191' '251' '267' '277' '287' '321' '245' '265' '301' '317'
 '299' '305' '473' '395' '423' '401' '365' '467' '343' '387' '459' '499'
 '449' '351' '457' '361' '373' '453' '491' '477' '331' '451' '435' '367'
 '503' '349' '333' '363' '337' '417' '441' '381' '425' '375' '335' '475'
 '355' '469' '411' '493' '379' '439' '371' '377' '353' '485' '487' '465'
 '383' '345' '359' '329' '327' '413' '447' '429' '397' '325' '385' '463'
 '437' '483' '369' '409' '393' '443' '415' '391' '479' '427' '505' '507'
 '341' '421' '433' '501' '445' '431' '399' '489' '389' '495' '357' '323'
 '40' '481' '036' '570' '800' '810' '550' '650' '700' '530' '730' '078'
 '186' '086' '461' '290' '240' '760' '150' '050' '188' '270']
FIPS_NAME: ['Plumas' 'Placer' 'El Dorado' ... "O'Brien" 'Gurabo Municipio' 'Garvin']
Shape: [b'\x00\x01\xad\x10\x00\x00\xe8d\xc2\x92_@^\xc0\xe0\xc8l\x98\xba\x04D@\xe8d\xc2\x92_@^\xc0\xe0\xc8l\x98\xba\x04D@|\x01\x00\x00\x00\xe8d\xc2\x92_@^\xc0\xe0\xc8l\x98\xba\x04D@\xfe'
 b'\x00\x01\xad\x10\x00\x00T\xb6\xeej\xe2\x19^\xc0\x90\xc6U]nwC@T\xb6\xeej\xe2\x19^\xc0\x90\xc6U]nwC@|\x01\x00\x00\x00T\xb6\xeej\xe2\x19^\xc0\x90\xc6U]nwC@\xfe'
 b'\x00\x01\xad\x10\x00\x00\xd0\xa5\xa0W\x13/^\xc0P\xbbf,\xf9}C@\xd0\xa5\xa0W\x13/^\xc0P\xbbf,\xf9}C@|\x01\x00\x00\x00\xd0\xa5\xa0W\x13/^\xc0P\xbbf,\xf9}C@\xfe'
 ...
 b'\x00\x01\xad\x10\x00\x00P\xb8\x1e\x85\xeb\x98^\xc0\x98\xc5\xfdG\xa6=D@P\xb8\x1e\x85\xeb\x98^\xc0\x98\xc5\xfdG\xa6=D@|\x01\x00\x00\x00P\xb8\x1e\x85\xeb\x98^\xc0\x98\xc5\xfdG\xa6=D@\xfe'
 b'\x00\x01\xad\x10\x00\x00x\xba_\xaa~9^\xc0\xb8dL\xc9\x0b\xd6B@x\xba_\xaa~9^\xc0\xb8dL\xc9\x0b\xd6B@|\x01\x00\x00\x00x\xba_\xaa~9^\xc0\xb8dL\xc9\x0b\xd6B@\xfe'
 b'\x00\x01\xad\x10\x00\x00\x1c\xa7\xe8H.5]\xc00`;\x18\xb1!A@\x1c\xa7\xe8H.5]\xc00`;\x18\xb1!A@|\x01\x00\x00\x00\x1c\xa7\xe8H.5]\xc00`;\x18\xb1!A@\xfe']

In [31]:
# Print unique values in each column with their counts
print("\nUnique values in each column with counts:")
for column in fires_data.columns:
    unique_counts = fires_data[column].value_counts()
    print(f"\n{column}:")
    print(unique_counts)

Unique values in each column with counts:

OBJECTID:
1          1
1253654    1
1253652    1
1253651    1
1253650    1
          ..
626819     1
626818     1
626817     1
626816     1
1880465    1
Name: OBJECTID, Length: 1880465, dtype: int64

FOD_ID:
1            1
1656874      1
1656872      1
1656871      1
1656870      1
            ..
676216       1
676215       1
676214       1
676213       1
300348399    1
Name: FOD_ID, Length: 1880465, dtype: int64

FPA_ID:
SFO-2015CACDFLNU003791     2
FS-1452833                 2
ICS209_2009_KS-DDQ-128     2
FS-1418826                 1
SFO-GA-FY2002-Dodge-092    1
                          ..
SFO-TX02240706-32931       1
SFO-TX02240706-32930       1
SFO-TX02240706-32928       1
SFO-TX02240706-32927       1
2015CAIRS26733926          1
Name: FPA_ID, Length: 1880462, dtype: int64

SOURCE_SYSTEM_TYPE:
NONFED       1362148
FED           481106
INTERAGCY      37211
Name: SOURCE_SYSTEM_TYPE, dtype: int64

SOURCE_SYSTEM:
ST-NASF        711236
DOI-WFMI       241423
FS-FIRESTAT    220356
ST-CACDF        87355
ST-NCNCS        65695
ST-GAGAS        65061
ST-MSMSS        60513
ST-TXTXS        57945
ST-ALALS        54951
ST-SCSCS        49281
ST-FLFLS        45077
IA-PRIITF       21802
FWS-FMIS        19327
ST-ORORS        18121
ST-LALAS        16172
ST-OKOKS        15397
ST-TNTNS        14777
ST-WIWIS        14323
ST-ARARS        11303
ST-VAVAS        10575
ST-MOMOS         9835
IA-HIWMO         9714
ST-WAWAS         9648
ST-MEMES         7252
ST-KYKYS         6519
ST-UTUTS         4470
ST-NMNMS         4433
IA-AKACC         3713
ST-AZAZS         3446
FA-NFIRS         3387
ST-CTCTS         3379
ST-SDSDS         3181
ST-MTMTS         2737
ST-COCOS         2433
ST-MIMIS         2139
IA-ICS209        1983
ST-WYWYS         1489
ST-NENES           17
Name: SOURCE_SYSTEM, dtype: int64

NWCG_REPORTING_AGENCY:
ST/C&L    1377090
FS         220497
BIA        119943
BLM         97034
IA          21841
NPS         20893
FWS         19331
TRIBE        3739
DOD            81
BOR            14
DOE             2
Name: NWCG_REPORTING_AGENCY, dtype: int64

NWCG_REPORTING_UNIT_ID:
USGAGAS    167123
USTXTXS    111362
USNCNCS    107424
USFLFLS     83024
USSCSCS     78977
            ...
USKSSTX         1
USKSSNX         1
USKSLGX         1
USKSGLX         1
USTNLHR         1
Name: NWCG_REPORTING_UNIT_ID, Length: 1640, dtype: int64

NWCG_REPORTING_UNIT_NAME:
Georgia Forestry Commission                      167123
Texas A & M Forest Service                       111362
North Carolina Forest Service                    107424
Florida Forest Service                            83024
South Carolina Forestry Commission                78977
                                                  ...
Oregon Coast National Wildlife Refuge Complex         1
Coleman National Fish Hatchery                        1
Steigerwald Lake National Wildlife Refuge             1
Cedar Breaks National Monument                        1
Fort Matanzas National Monument                       1
Name: NWCG_REPORTING_UNIT_NAME, Length: 1635, dtype: int64

SOURCE_REPORTING_UNIT:
GAGAS    97844
SCSCS    52064
TXTXS    40366
FLFLS    37945
NCNCS    37255
         ...
10755        1
09002        1
10170        1
3720         1
NMGUA        1
Name: SOURCE_REPORTING_UNIT, Length: 4992, dtype: int64

SOURCE_REPORTING_UNIT_NAME:
Georgia Forestry Commission                97844
Fire Department of New York                75461
South Carolina Forestry Commission         52064
Mississippi Forestry Commission            46396
Texas Forest Service                       42675
                                           ...
MINGO NWR                                      1
Eagle Mountain VFD                             1
Slade National Wildlife Refuge                 1
Chase Lake National Wildlife Refuge            1
BENTON LAKE WETLAND MANAGEMENT DISTRICT        1
Name: SOURCE_REPORTING_UNIT_NAME, Length: 4441, dtype: int64

LOCAL_FIRE_REPORT_ID:
001       8189
002       4960
1         3652
2         3554
3         3494
          ...
554037       1
500158       1
525680       1
506923       1
535436       1
Name: LOCAL_FIRE_REPORT_ID, Length: 13508, dtype: int64

LOCAL_INCIDENT_ID:
001                3839
1                  3258
2                  2874
3                  2647
002                2489
                   ...
NY5290-2007-317       1
NY5290-2007-310       1
NY5290-2007-309       1
NY5290-2007-300       1
000366                1
Name: LOCAL_INCIDENT_ID, Length: 565914, dtype: int64

FIRE_CODE:
D44Z    9451
5555    5144
D5GJ    3459
0001    3329
0000    1928
        ...
B05N       1
B1FE       1
B1TJ       1
B2GG       1
J48B       1
Name: FIRE_CODE, Length: 172446, dtype: int64

FIRE_NAME:
GRASS FIRE                   3983
NA                           3214
UNKNOWN                      3154
LOCAL                        2068
STATE                        1423
                             ...
MARTHA CHAPEL FIRE              1
EAST GARGUS FIRE                1
BURNING DOG FIRE                1
MCIVEN FIRE                     1
BARKER BL  BIG_BEAR_LAKE_       1
Name: FIRE_NAME, Length: 493633, dtype: int64

ICS_209_INCIDENT_NUMBER:
OK-OSA-100020          53
MT-BRF-000135          46
WA-OWF-000583          41
CA-MNF-000663          39
ID-PAF-006068          39
                       ..
FL-FLS-2009-11-0596     1
FL-FLS-2009-11-0589     1
FL-FLS-2009-11-0550     1
FL-FLS-2009-11-0539     1
474967                  1
Name: ICS_209_INCIDENT_NUMBER, Length: 22737, dtype: int64

ICS_209_NAME:
OSAGE-MIAMI COMPLEX          53
Selway-Salmon WFU Complex    46
YAKIMA COMPLEX               41
South Fork Complex           39
Yolla Bolly Complex          39
                             ..
MOORE FORK                    1
GRASSY BR.                    1
WESLEY HOLLOW                 1
ELM SHOAL                     1
Popcorn                       1
Name: ICS_209_NAME, Length: 19573, dtype: int64

MTBS_ID:
KY3686008359020011102    12
ID4542411459020120730     9
ID4568011472320070706     8
MT4574610716620120731     7
OR4493112043020110824     7
                         ..
AK6469615502220070705     1
AK6539014123320070705     1
AK6700815143220070708     1
AK6641014362620070708     1
CA3944512141720130816     1
Name: MTBS_ID, Length: 10481, dtype: int64

MTBS_FIRE_NAME:
UNNAMED          752
COTTONWOOD        24
CANYON            14
BEAR CREEK        12
WILLOW            12
                ...
SULUKNA RIVER      1
HOLLY LAKES        1
RAY RIVER          1
OLD DUMMY          1
SWEDES             1
Name: MTBS_FIRE_NAME, Length: 8133, dtype: int64

COMPLEX_NAME:
OSAGE-MIAMI COMPLEX          54
TILLER COMPLEX               50
MOTORWAY COMPLEX             49
SELWAY-SALMON WFU COMPLEX    46
SOUTH FORK COMPLEX           42
                             ..
CEDAR COMPLEX                 1
KERR COUNTY COMPLEX           1
GARVENS STORE COMPLEX         1
ANDREW COUNTY COMPLEX         1
JAMUL COMPLEX                 1
Name: COMPLEX_NAME, Length: 1416, dtype: int64

FIRE_YEAR:
2006    114004
2000     96416
2007     95573
2011     90552
1999     89363
2005     88604
2001     86587
2008     85378
2010     79889
2009     78325
1994     75955
2002     75656
1996     75574
2015     74491
2012     72769
1995     71472
2004     69279
1998     68370
2003     68261
1992     67975
2014     67753
2013     64780
1993     61989
1997     61450
Name: FIRE_YEAR, dtype: int64

DISCOVERY_DATE:
2454506.5    1208
2453441.5    1177
2453798.5    1121
2455611.5    1108
2449430.5    1070
             ...
2450836.5       4
2450828.5       3
2448995.5       2
2448996.5       2
2448998.5       2
Name: DISCOVERY_DATE, Length: 8766, dtype: int64

DISCOVERY_DOY:
185    12875
186    11535
101     9261
67      9260
108     9256
       ...
351     1493
349     1419
348     1347
359     1290
366      544
Name: DISCOVERY_DOY, Length: 366, dtype: int64

DISCOVERY_TIME:
1400    20981
1500    20020
1600    18234
1300    17280
1700    14027
        ...
0427       22
0349       20
0403       20
0413       19
0409       17
Name: DISCOVERY_TIME, Length: 1440, dtype: int64

STAT_CAUSE_CODE:
5.0     429028
9.0     323805
7.0     281455
1.0     278468
13.0    166723
2.0     147612
4.0      76139
8.0      61167
3.0      52869
6.0      33455
11.0     14448
10.0     11500
12.0      3796
Name: STAT_CAUSE_CODE, dtype: int64

STAT_CAUSE_DESCR:
Debris Burning       429028
Miscellaneous        323805
Arson                281455
Lightning            278468
Missing/Undefined    166723
Equipment Use        147612
Campfire              76139
Children              61167
Smoking               52869
Railroad              33455
Powerline             14448
Fireworks             11500
Structure              3796
Name: STAT_CAUSE_DESCR, dtype: int64

CONT_DATE:
2455611.5    841
2457067.5    668
2449056.5    649
2450137.5    631
2448683.5    631
            ...
2453363.5      1
2453362.5      1
2455179.5      1
2457391.5      1
2457388.5      1
Name: CONT_DATE, Length: 8760, dtype: int64

CONT_DOY:
185.0    7325
186.0    7091
184.0    5389
187.0    5268
204.0    5246
         ...
348.0     604
342.0     600
358.0     552
359.0     523
366.0     135
Name: CONT_DOY, Length: 366, dtype: int64

CONT_TIME:
1800    38078
1600    22167
1700    20606
1200    19276
1500    18757
        ...
0421       14
0524       14
0541       13
0543       13
0429       13
Name: CONT_TIME, Length: 1441, dtype: int64

FIRE_SIZE:
0.10       459145
1.00       221680
0.50       113222
2.00       109493
0.20        75302
            ...
29.08           1
28.99           1
1518.00         1
9324.00         1
24.74           1
Name: FIRE_SIZE, Length: 13637, dtype: int64

FIRE_SIZE_CLASS:
B    939376
A    666919
C    220077
D     28427
E     14107
F      7786
G      3773
Name: FIRE_SIZE_CLASS, dtype: int64

LATITUDE:
47.866600    955
33.335300    706
33.351700    605
47.883300    585
17.970539    571
            ...
37.709628      1
38.374578      1
39.431971      1
38.730903      1
34.263217      1
Name: LATITUDE, Length: 894061, dtype: int64

LONGITUDE:
-110.451800    792
-123.684500    745
-66.246414     571
-110.450700    507
-66.386131     384
              ...
-71.450833       1
-148.833333      1
-147.266667      1
-71.518333       1
-116.830950      1
Name: LONGITUDE, Length: 997536, dtype: int64

OWNER_CODE:
14.0    1050835
8.0      314822
5.0      188338
2.0      106819
13.0      71881
1.0       63278
7.0       30790
3.0       17524
4.0       12191
9.0        8952
6.0        6452
12.0       4236
15.0       2206
11.0       1841
10.0        285
0.0          15
Name: OWNER_CODE, dtype: int64

OWNER_DESCR:
MISSING/NOT SPECIFIED    1050835
PRIVATE                   314822
USFS                      188338
BIA                       106819
STATE OR PRIVATE           71881
BLM                        63278
STATE                      30790
NPS                        17524
FWS                        12191
TRIBAL                      8952
OTHER FEDERAL               6452
MUNICIPAL/LOCAL             4236
UNDEFINED FEDERAL           2206
COUNTY                      1841
BOR                          285
FOREIGN                       15
Name: OWNER_DESCR, dtype: int64

STATE:
CA    189550
GA    168867
TX    142021
NC    111277
FL     90261
SC     81315
NY     80870
MS     79230
AZ     71586
AL     66570
OR     61088
MN     44769
OK     43239
MT     40767
NM     37478
ID     36698
CO     34157
WA     33513
WI     31861
AR     31663
TN     31154
SD     30963
UT     30725
LA     30013
KY     27089
NJ     25949
PR     22081
WV     21967
VA     21833
MO     17953
NV     16956
ND     15201
WY     14166
ME     13150
AK     12843
MI     10502
HI      9895
PA      8712
NE      7973
KS      7673
CT      4976
IA      4134
MD      3622
OH      3479
MA      2626
NH      2452
IL      2327
IN      2098
RI       480
VT       456
DE       171
DC        66
Name: STATE, dtype: int64

COUNTY:
5                                                     7576
Lincoln                                               7405
SUFFOLK                                               7373
Polk                                                  6955
Washington                                            6916
                                                      ...
KALAMAZOO                                                1
WEXFORD                                                  1
BARAGA                                                   1
ARENAC                                                   1
HARDY                                                    1
Name: COUNTY, Length: 3455, dtype: int64

FIPS_CODE:
005    29069
003    28850
029    28519
001    27042
007    22230
       ...
760        1
150        1
570        1
40         1
650        1
Name: FIPS_CODE, Length: 285, dtype: int64

FIPS_NAME:
Washington        11014
Lincoln           10571
Jackson            9902
Marion             8908
Cherokee           8558
                  ...
Terrebonne            1
Milwaukee             1
Kingfisher            1
Glacier County        1
Garvin                1
Name: FIPS_NAME, Length: 1698, dtype: int64

Shape:
b'\x00\x01\xad\x10\x00\x00\xb0\xd19?\xc5\x8fP\xc0 ~p>u\xf81@\xb0\xd19?\xc5\x8fP\xc0 ~p>u\xf81@|\x01\x00\x00\x00\xb0\xd19?\xc5\x8fP\xc0 ~p>u\xf81@\xfe'                                                 571
b'\x00\x01\xad\x10\x00\x000>\xcc^\xb6\x98P\xc0Ps\x9dFZ\xfe1@0>\xcc^\xb6\x98P\xc0Ps\x9dFZ\xfe1@|\x01\x00\x00\x000>\xcc^\xb6\x98P\xc0Ps\x9dFZ\xfe1@\xfe'                                                 384
b'\x00\x01\xad\x10\x00\x00(\x87\x16\xd9\xce\xeb^\xc0\x98\x97n\x12\x83\x88D@(\x87\x16\xd9\xce\xeb^\xc0\x98\x97n\x12\x83\x88D@|\x01\x00\x00\x00(\x87\x16\xd9\xce\xeb^\xc0\x98\x97n\x12\x83\x88D@\xfe'    355
b'\x00\x01\xad\x10\x00\x00d\xc4\x05\xa0Q\x87P\xc0@\xb4s\x9a\x05\xfa1@d\xc4\x05\xa0Q\x87P\xc0@\xb4s\x9a\x05\xfa1@|\x01\x00\x00\x00d\xc4\x05\xa0Q\x87P\xc0@\xb4s\x9a\x05\xfa1@\xfe'                      352
b'\x00\x01\xad\x10\x00\x00$~\x8c\xb9k5]\xc0\xb8Y\xf5\xb9\xdaJ@@$~\x8c\xb9k5]\xc0\xb8Y\xf5\xb9\xdaJ@@|\x01\x00\x00\x00$~\x8c\xb9k5]\xc0\xb8Y\xf5\xb9\xdaJ@@\xfe'                                        336
                                                                                                                                                                                                      ...
b'\x00\x01\xad\x10\x00\x00\x84\x9d)t^\x89T\xc0\x80B\xbf!\x1a\x81A@\x84\x9d)t^\x89T\xc0\x80B\xbf!\x1a\x81A@|\x01\x00\x00\x00\x84\x9d)t^\x89T\xc0\x80B\xbf!\x1a\x81A@\xfe'                                 1
b'\x00\x01\xad\x10\x00\x00l\xa0<\x03\x95\x81T\xc0\x88\xfa\x969]\x86A@l\xa0<\x03\x95\x81T\xc0\x88\xfa\x969]\x86A@|\x01\x00\x00\x00l\xa0<\x03\x95\x81T\xc0\x88\xfa\x969]\x86A@\xfe'                        1
b'\x00\x01\xad\x10\x00\x00\xc4\xb1\xfd}\xa9\x7fT\xc0\x00\x97\x9b=\n_A@\xc4\xb1\xfd}\xa9\x7fT\xc0\x00\x97\x9b=\n_A@|\x01\x00\x00\x00\xc4\xb1\xfd}\xa9\x7fT\xc0\x00\x97\x9b=\n_A@\xfe'                     1
b'\x00\x01\xad\x10\x00\x00Xks\x8c\xb9\x81T\xc0\xa0\x92\xc4\x16+\x92A@Xks\x8c\xb9\x81T\xc0\xa0\x92\xc4\x16+\x92A@|\x01\x00\x00\x00Xks\x8c\xb9\x81T\xc0\xa0\x92\xc4\x16+\x92A@\xfe'                        1
b'\x00\x01\xad\x10\x00\x00\x1c\xa7\xe8H.5]\xc00`;\x18\xb1!A@\x1c\xa7\xe8H.5]\xc00`;\x18\xb1!A@|\x01\x00\x00\x00\x1c\xa7\xe8H.5]\xc00`;\x18\xb1!A@\xfe'                                                   1
Name: Shape, Length: 1569708, dtype: int64

In [13]:
fires_data_shape = pd.read_sql(sql = 'select * from idx_Fires_Shape', con = conn)

In [14]:
fires_data_shape.head().T

                 0             1             2             3             4
pkid  1.064078e+06  1.064195e+06  1.729139e+06  1.064196e+06  1.064225e+06
xmin -1.668694e+02 -1.662693e+02 -1.661667e+02 -1.661527e+02 -1.660294e+02
xmax -1.668694e+02 -1.662693e+02 -1.661667e+02 -1.661527e+02 -1.660294e+02
ymin  6.598260e+01  6.511590e+01  6.583330e+01  6.518259e+01  6.592690e+01
ymax  6.598260e+01  6.511591e+01  6.583331e+01  6.518260e+01  6.592690e+01

In [15]:
geometry_columns = pd.read_sql(sql = 'select * from geometry_columns',con = conn)

In [19]:
geometry_columns.tail()

,f_table_name,f_geometry_column,geometry_type,coord_dimension,srid,spatial_index_enabled
0,fires,shape,1,2,4269,1

In [20]:
geometry_columns.head()

,f_table_name,f_geometry_column,geometry_type,coord_dimension,srid,spatial_index_enabled
0,fires,shape,1,2,4269,1

In [22]:
idx_Fires_Shape_rowid = pd.read_sql(sql = 'select * from idx_Fires_Shape_rowid', con = conn)

In [25]:
idx_Fires_Shape_rowid.head()

   rowid  nodeno
0      1    2709
1      2    2750
2      3    6313
3      4    5777
4      5    5777